const data = [
    {
        id:101,
        imgsrc:"https://m.media-amazon.com/images/I/817WWpaFo1L._AC_UY327_FMwebp_QL65_.jpg",
        name:"Samsung Galaxy M14 5G",
        desc:""
    },
    {
        id:102,
        imgsrc:"https://m.media-amazon.com/images/I/81MZRUuHJIL._AC_UY327_FMwebp_QL65_.jpg",
        name:"",
        desc:""
    },
    {
        id:103,
        imgsrc:"https://m.media-amazon.com/images/I/81t6Av5DvXL._AC_UY327_FMwebp_QL65_.jpg",
        name:"",
        desc:""
    },
    {
        id:104,
        imgsrc:"https://m.media-amazon.com/images/I/81ogvU1j6qL._AC_UY327_FMwebp_QL65_.jpg",
        name:"",
        desc:""
    },
    {
        id:105,
        imgsrc:"https://m.media-amazon.com/images/I/71V--WZVUIL._AC_UY327_FMwebp_QL65_.jpg",
        name:"",
        desc:""
    },
    {
        id:106,
        imgsrc:"https://m.media-amazon.com/images/I/81LVUqx+4HL._AC_UY327_FMwebp_QL65_.jpg",
        name:"",
        desc:""
    },
    {
        id:107,
        imgsrc:"https://m.media-amazon.com/images/I/814ePfNubRL._AC_UY327_FMwebp_QL65_.jpg",
        name:"",
        desc:""
    },
    {
        id:108,
        imgsrc:"https://m.media-amazon.com/images/I/812YsUxpyfL._AC_UY327_FMwebp_QL65_.jpg",
        name:"",
        desc:""
    },
    {
        id:109,
        imgsrc:"https://m.media-amazon.com/images/I/819bwF7gjfL._AC_UY327_FMwebp_QL65_.jpg",
        name:"",
        desc:""
    },
    {
        id:110,
        imgsrc:"https://m.media-amazon.com/images/I/812YsUxpyfL._AC_UY327_FMwebp_QL65_.jpg",
        name:"",
        desc:""
    },
    {
        id:111,
        imgsrc:"https://m.media-amazon.com/images/I/51PqaHZDiNL._AC_UY327_FMwebp_QL65_.jpg",
        name:"",
        desc:""
    },
    {
        id:112,
        imgsrc:"https://m.media-amazon.com/images/I/810fCELNzvL._AC_UY327_FMwebp_QL65_.jpg",
        name:"",
        desc:""
    },
    {
        id:113,
        imgsrc:"https://m.media-amazon.com/images/I/81RR0TAz+5L._AC_UY327_FMwebp_QL65_.jpg",
        name:"",
        desc:""
    },
    {
        id:114,
        imgsrc:"https://m.media-amazon.com/images/I/8104evx11QL._AC_UY327_FMwebp_QL65_.jpg",
        name:"",
        desc:""
    },
    {
        id:115,
        imgsrc:"https://m.media-amazon.com/images/I/81WPIz1l5wL._AC_UY327_FMwebp_QL65_.jpg",
        name:"",
        desc:""
    },
    {
        id:116,
        imgsrc:"https://m.media-amazon.com/images/I/71Ftzmh3XWL._AC_UY327_FMwebp_QL65_.jpg",
        name:"",
        desc:""
    },
    {
        id:117,
        imgsrc:"https://m.media-amazon.com/images/I/61d8nhX80WL._AC_UY327_FMwebp_QL65_.jpg",
        name:"",
        desc:""
    },
    {
        id:118,
        imgsrc:"https://m.media-amazon.com/images/I/61M0tGMbBPL._AC_UY327_FMwebp_QL65_.jpg",
        name:"",
        desc:""
    },
    {
        id:119,
        imgsrc:"https://m.media-amazon.com/images/I/71LtFZN0-7L._AC_UY327_FMwebp_QL65_.jpg",
        name:"",
        desc:""
    },
    {
        id:120,
        imgsrc:"https://m.media-amazon.com/images/I/81bh6SxXQ+L._AC_UY327_FMwebp_QL65_.jpg",
        name:"",
        desc:""
    },
    {
        id:121,
        imgsrc:"https://m.media-amazon.com/images/I/81WPIz1l5wL._AC_UY327_FMwebp_QL65_.jpg",
        name:"",
        desc:""
    },
    {
        id:122,
        imgsrc:"https://m.media-amazon.com/images/I/81WPIz1l5wL._AC_UY327_FMwebp_QL65_.jpg",
        name:"",
        desc:""
    },
    {
        id:123,
        imgsrc:"https://m.media-amazon.com/images/I/81t6Av5DvXL._AC_UY327_FMwebp_QL65_.jpg",
        name:"",
        desc:""
    },
]

data.map((item)=> {
    console.log(`ID: ${item.id}`);
    console.log(`Image: ${item.imgsrc}`);
    console.log(`Name: ${item.name}`);
    console.log(`Desc: ${item.desc}`);
})